version: '3.3'

services:
  web:
    build: ./app
    command: gradle --no-daemon :server:run
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
      - POSTGRES_DB=dashboard
